version: '2'

services:

  wyf-app:
    build:
      context: .
      dockerfile: ./.docker/wyf-app.development.dockerfile
    command: npm start
    container_name: wyf-app-start
    image: wyf-app
    networks:
      - dev-network
    ports:
      - '3000:3000'
      
networks:
  dev-network:
    driver: bridge