FROM php:5.6-apache
LABEL maintainer "Tech Ninja <4umninja@gmail.com>"
VOLUME ["/dist"]
EXPOSE [${PORT}, 1337, 4040]

# Enable Apache Rewrite Module
RUN a2enmod rewrite

# Install PHP extensions
RUN apt-get update && apt-get install -y libpng12-dev libjpeg-dev libmcrypt-dev zip unzip && rm -rf /var/lib/apt/lists/* \
	&& docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
	&& docker-php-ext-install gd
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install mcrypt
RUN docker-php-ext-install zip

# Define Joomla version and expected SHA1 signature
ENV JOOMLA_DB_HOST localhost
# ENV MYSQL_PORT_3306_TCP 3306
ENV JOOMLA_DB_NAME whittle_scrap
ENV JOOMLA_DB_USER root
ENV JOOMLA_DB_PASSWORD andrene

# Define Joomla configurations
ENV JOOMLA_VERSION 3.7.0
ENV JOOMLA_SHA1 4ad7d7c88aae9d1f86c04dae1a497b6f300f15d2

# Download package and extract to web volume
RUN curl -o joomla.zip -SL https://github.com/joomla/joomla-cms/releases/download/${JOOMLA_VERSION}/Joomla_${JOOMLA_VERSION}-Stable-Full_Package.zip \
	&& echo "$JOOMLA_SHA1 *joomla.zip" | sha1sum -c - \
	&& mkdir /usr/src/joomla \
	&& unzip joomla.zip -d /usr/src/joomla \
	&& rm joomla.zip \
	&& chown -R www-data:www-data /usr/src/joomla

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]







# Docker-Compose joomla config

  joomla:
    image: joomla
    links:
      - joomladb:mysql
    ports:
      - 8080:80

  joomladb:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: admin
